version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: kokodiary-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: kokodiary-backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/kokodiary?authSource=admin
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=production

  mongodb:
    image: mongo:latest
    container_name: kokodiary-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=kokodiary
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: kokodiary-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
